---

- name: Deploy mock v2 service
  hosts: keystone_all
  tasks:
    - name: Install pip requirements
      pip:
        name: flask
        virtualenv: /openstack/venvs/keystone-untagged

    - name: Drop apache configuration
      template:
        src=templates/etc/apache2/sites-enabled/mock-v2.conf
        dest=/etc/apache2/sites-enabled/mock-v2.conf
        mode=0744

    - name: Drop WSGI script
      template:
        src=templates/var/www/cgi-bin/mock-v2.wsgi
        dest=/var/www/cgi-bin/mock-v2.wsgi
        mode=0755
        owner=keystone
        group=keystone

    - name: Restart apache
      service:
        name=apache2
        state=restarted
