---

- name: Deploy capstone
  hosts: keystone_all
  roles:
    - pip_install
    - os_keystone
  post_tasks:
    - stat: path=/usr/bin/plight
      register: plight
    - include: tasks/install_plight.yml
      when: not plight.stat.exists
    - include: tasks/capstone_local_install.yml
    - include: tasks/capstone_post_tasks.yml
  vars:
    # NOTE(lbragstad): These variables are required regardless if we're
    # deploying venvs to staging/production or if we're installing from
    # source locally.
    keystone_requirements_git_repo: https://github.com/openstack/requirements
    keystone_git_repo: https://github.com/openstack/keystone
    keystone_git_install_branch: stable/mitaka
    keystone_database_enabled: false
    keystone_service_setup: false
    keystone_token_provider: capstone
    keystone_database_connection_string: none
    keystone_public_endpoint: "https://identity.api.rackspacecloud.com"
    keystone_service_adminuri: "https://identity.api.rackspacecloud.com"
    internal_lb_vip_address: localhost
    keystone_auth_admin_token: none
    keystone_rabbitmq_password: none
    galera_client_drop_config_file: false
    keystone_ssl: true
    keystone_service_internaluri_proto: "https"
    keystone_service_port: "8443"
    keystone_keystone_conf_overrides:
      DEFAULT:
        log_config_append: /etc/keystone/logging.conf
      auth:
        method: password
        password: capstone
      oslo_policy:
        policy_file: /etc/capstone/policy.json
    service_user_role_id: "admin"
