---

- name: Deploy capstone
  hosts: keystone_all
  roles:
    - os_keystone
  post_tasks:
    - name: Install capstone from source
      pip:
        name: "git+https://github.com/rackerlabs/capstone#egg=capstone"
        virtualenv: "{{ keystone_venv_bin | dirname }}"
        virtualenv_site_packages: "no"
        extra_args: "{{ pip_install_options|default('') }}"
      when: (venv_location is undefined and capstone_version is undefined)
      tags:
        - capstone
    - name: Create capstone dir
      file:
        path: /etc/capstone
        state: directory
        owner: keystone
      tags:
        - capstone
    - name: Drop capstone.conf
      template:
        src: templates/etc-capstone.conf
        dest: /etc/capstone/capstone.conf
        owner: keystone
      tags:
        - capstone
    - name: Drop keystone logging config
      template:
        src: templates/logging.conf
        dest: /etc/keystone/logging.conf
        owner: keystone
      tags:
        - capstone
    - name: Restart apache
      service:
        name: "apache2"
        state: "restarted"
        pattern: "apache2"
  vars:
    keystone_venv_tag: "{{ capstone_version }}"
    keystone_venv_bin: "/openstack/venvs/keystone-{{ capstone_version }}/bin"
    keystone_venv_download_url: "{{ venv_location }}/{{ capstone_version }}.tgz"
    keystone_git_install_branch: stable/liberty
    keystone_developer_mode: false
    keystone_database_enabled: false
    keystone_service_setup: false
    keystone_token_provider: capstone
    keystone_database_connection_string: none
    keystone_public_endpoint: "https://identity.api.rackspacecloud.com"
    keystone_service_adminuri: "https://identity.api.rackspacecloud.com"
    internal_lb_vip_address: localhost
    keystone_auth_admin_token: none
    keystone_rabbitmq_password: none
    galera_client_drop_config_file: false
    pip_upstream_url: "{{ pip_url|default('https://bootstrap.pypa.io/get-pip.py') }}"
    keystone_keystone_conf_overrides:
      DEFAULT:
        log_config_append: /etc/keystone/logging.conf
      auth:
        method: password
        password: capstone
    keystone_requires_pip_packages:
      - virtualenv-tools
      - httplib2
    pip_global_conf_overrides:
      global:
        index-url: "{{ pypi_server|default('https://pypi.python.org/simple/') }}"
        find-links: "{{ pypi_server|default('https://pypi.python.org/simple/') }}"
        trusted-host: "{{ trusted_pypi|default('https://pypi.python.org/simple/') }}"
        no-index: false
        allow-all-external: true
        no-allow-insecure: false
    pip_links:
      - name: internal
        link: "{{ pypi_server|default('https://pypi.python.org/simple/') }}"
