---

- name: Deploy mock v2 service
  hosts: keystone_all
  tasks:
    - name: Install pip requirements
      pip:
        name=flask

    - name: Create directory for source
      file:
        path=/opt/mock_v2/
        state=directory
        owner=keystone
        group=keystone

    - name: Install mock_v2 source
      template:
        src=../capstone/tests/integration/mock_v2/service.py
        dest=/opt/mock_v2/service.py
        owner=keystone
        group=keystone
        mode=0755

    - name: Drop apache configuration
      template:
        src=templates/etc/apache2/sites-enabled/mock-v2.conf
        dest=/etc/apache2/sites-enabled/mock-v2.conf
        mode=0744

    - name: Restart apache
      service:
        name=apache2
        state=restarted
