---

- name: Deploy capstone
  hosts: keystone_all
  roles:
    - pip_install
    - os_keystone
  post_tasks:
    - include: tasks/plight.yml
    - include: tasks/capstone_local_install.yml
      when: (venv_location is undefined and capstone_version is undefined)
    - include: tasks/capstone_post_install.yml
  vars:
    # NOTE(lbragstad): These variables are required regardless if we're
    # deploying venvs to staging/production or if we're installing from
    # source locally.
    keystone_git_install_branch: stable/liberty
    keystone_database_enabled: false
    keystone_service_setup: false
    keystone_token_provider: capstone
    keystone_database_connection_string: none
    keystone_public_endpoint: "https://identity.api.rackspacecloud.com"
    keystone_service_adminuri: "https://identity.api.rackspacecloud.com"
    internal_lb_vip_address: localhost
    keystone_auth_admin_token: none
    keystone_rabbitmq_password: none
    galera_client_drop_config_file: false
    keystone_keystone_conf_overrides:
      DEFAULT:
        log_config_append: /etc/keystone/logging.conf
      auth:
        method: password
        password: capstone
      service_admin:
        username: "{{ service_user_name }}"
        password: "{{ service_user_password }}"
        project_id: "{{ service_user_account_number }}"
      rackspace:
        base_url: "{{ rackspace_base_url|default('https://identity.api.rackspacecloud.com/v2.0') }}"
