---
capstone:
  image: capstone:latest
  ports:
    - 5000:5000
    - 35357:35357
  environment:
    SERVICE_USER_NAME: admin
    SERVICE_USER_PASSWORD: secrete
    RACKSPACE_BASE_URL: https://identity.api.rackspacecloud.com/v2.0
