---

- name: Install capstone from source
  pip:
    name: "{{ inventory_dir.split('/')[0:-1]|join('/') }}"
    virtualenv: "{{ keystone_venv_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: "{{ pip_install_options|default('') }}"
  when: (venv_location is undefined and capstone_version is undefined)
  tags:
    - capstone
