---

- name: Add plight repository
  apt_repository:
    repo: "{{ plight_repository }}"
    state: "present"
    update_cache: yes
  tags:
    - capstone
- name: Install plight
  apt:
    pkg: plight
    state: installed
    force: yes
  retries: 5
  delay: 2
  tags:
    - capstone
- name: Ensure plight is running
  command: service plightd start
  tags:
    - capstone
