---

- name: Add plight repository
  apt_repository:
    repo: "{{ plight_repo }}"
    state: "present"
    update_cache: yes
  tags:
    - capstone
- name: Install plight
  apt:
    pkg: plight
    state: installed
    force: yes
  retries: 5
  delay: 2
  tags:
    - capstone
- name: Ensure plight is running
  service:
    name: plightd
    state: started
    enabled: yes
  tags:
    - capstone
