---

# for some reason this is needed in staging but not here?!
#- name: Add apt key for plight
#  apt_key:
#    id: "{{ plight_hash_id }}"
#    keyserver: "{{ plight_keyserver }}"
#    state: "present"
#  tags:
#    - capstone
- name: Add plight repository
  apt_repository:
    repo: "{{ plight_repository }}"
    state: "present"
    update_cache: yes
  tags:
    - capstone
- name: Install plight
  apt:
    pkg: plight
    state: installed
    force: yes
  retries: 5
  delay: 2
  tags:
    - capstone
